### ISSUE TITLE
TypeError: this._socket.write is not a function

### ISSUE THREAD

**Issue by superhero** [nodemailer/smtp-connection#53]
I'm not sure if I miss understood something, or if this is a bug. Please advice.

**code**
```
resolveMx(to.split('@').pop(), (error, addresses) =>
{
  console.log('mail:', mail);

  addresses.sort((a, b) => a.priority > b.priority);

  const client = new SMTPConnection(
  {
    host              : addresses[0],
    opportunisticTLS  : true,
    connectionTimeout : 5000,
    greetingTimeout   : 3000,
    logger            : true,
    debug             : true,
    tls               : { rejectUnauthorized : false }
  });

  client.connect(() => console.log('connected callback'));

  client.on('error',    (error) => console.log('error:', error));
  client.on('connect',  ()      => console.log('connected'));
  client.on('end',      ()      => console.log('end'));

  client.send(
  {
    from : 'erik.landvall@example.es',
    to   : to
  },
  mail.body,
  (error, info) =>
  {
    console.log('error:', error);
    console.log('info:',  info);
    client.quit();
  });
});
```

**output**
```
mail: { head: 
   { 'content-type': 'text/plain',
     from: 'Erik Landvall <erik.landvall@example.es>',
     to: [ 'erik.landvall@example.es' ],
     subject: 'Test - Subject',
     'message-id': '<3b72f71b-23e0-7702-58d1-16d5cac7ab06@example.es>',
     'x-mailer': 'nodemailer (2.6.4; +https://nodemailer.com/;',
     'smtp/2.7.2[client': '2.12.0])',
     'content-transfer-encoding': '7bit',
     date: 'Mon, 10 Oct 2016 14:10:22 +0000',
     'mime-version': '1.0' },
  body: 'Test - Message' }
[2016-10-10 14:10:22] DEBUG: [lyZPMV5vQ] C: MAIL FROM:<erik.landvall@example.es>
/opt/smtp/node_modules/smtp-connection/lib/smtp-connection.js:695
    this._socket.write(new Buffer(str + '\r\n', 'utf-8'));
                 ^

TypeError: this._socket.write is not a function
    at SMTPConnection._sendCommand (/opt/smtp/node_modules/smtp-connection/lib/smtp-connection.js:695:18)
    at SMTPConnection._setEnvelope (/opt/smtp/node_modules/smtp-connection/lib/smtp-connection.js:791:10)
    at SMTPConnection.send (/opt/smtp/node_modules/smtp-connection/lib/smtp-connection.js:383:10)
    at resolveMx (/opt/smtp/service/server/on-data.js:84:16)
    at QueryReqWrap.asyncCallback [as callback] (dns.js:65:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:218:10)

```

**Comment by andris9** [comment]
You have to wait until `connect()` finishes before you can send anything

**Comment by superhero** [comment]
haha, yes, mondays :D thanks...
