### ISSUE TITLE
this._socket.write(new Buffer(str + '\r\n', 'utf-8')); Login method never works

### ISSUE THREAD

**Issue by wzup** [nodemailer/smtp-connection#55]
It seems that `connection.login` doesn't work. At least if one follows yours documentation.

I get this error:
```
C:\Users\user\smtp\node_modules\smtp-connection\lib\smtp-connection.js:695
    this._socket.write(new Buffer(str + '\r\n', 'utf-8'));
                 ^
TypeError: this._socket.write is not a function
    at SMTPConnection._sendCommand (C:\Users\user\smtp\node_modules\smtp-connection\lib\smtp-connection.js:695:18)
    at SMTPConnection.login (C:\Users\user\smtp\node_modules\smtp-connection\lib\smtp-connection.js:321:18)
    at Object.<anonymous> (C:\Users\user\smtp\client_send_google.js:38:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
[Finished in 0.3s with exit code 1]
```

Code:
```
let os = require('os');
let SMTPConnection = require('smtp-connection');
let wellknown = require('nodemailer-wellknown');

let options = Object.assign({}, wellknown('Gmail'), {
    secure: true,
})
let client = new SMTPConnection(options);

client.login({
    user: 'oldjknsodfjqn',
    pass: 'osdkjnoodinfmws'
}, connectCb)

function connectCb(err) {
    let message = 'foo'
    let envelope = { ... }
    client.send(envelope, message, (err, info) => {
        ...
    });
}
```

**Comment by andris9** [comment]
Do not call `login` until you have the connection set up.
