### ISSUE TITLE
this._socket.write is not a function

### ISSUE THREAD

**Issue by ScriptPup** [nodemailer/smtp-connection#56]
I'm not sure what the problem here is... I'm trying to set up an SMTP client to connect to office 365 as my relay (using this article as reference: https://support.office.com/en-us/article/How-to-set-up-a-multifunction-device-or-application-to-send-email-using-Office-365-69f58e99-c550-4274-ad18-c805d654b4c4) 

Full error:

```
\node_modules\smtp-connection\lib\smtp-connection.js:695
    this._socket.write(new Buffer(str + '\r\n', 'utf-8'));
                 ^

TypeError: this._socket.write is not a function
    at SMTPConnection._sendCommand smtp-connection\lib\smtp-connection.js:695:18)
    at SMTPConnection.login (node_modules\smtp-connection\lib\smtp-connection.js:321:18)
    at new email (Server\email.js:15:15)
    at Object.<anonymous> (Server.js:12:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

Here's the code causing this:
var SMTPConnection = require('smtp-connection');

```
email = function(){
    var Self = this;
    this.opts = {
        port: 587,
        host: "smtp.office365.com",
        requireTLS: true
    }
    this.auth = {
        user: 'myemail@office365domain.com',
        pass: 'MyPass'
    }
    this.SMTP = new SMTPConnection(this.opts);
    this.SMTP.login(this.auth,function(res){
        if(res){ Self.verified = false; console.error(res); this.SMTP.disconnect(); return; }
        else { Self.verified = true; console.log("Successful connection!"); this.SMTP.disconnect(); return; }
    })
}
```

**Comment by andris9** [comment]
do not call login or send before the connection is actually set up. See [here](https://github.com/nodemailer/smtp-connection/blob/master/test/smtp-connection-test.js#L301-L317) for an example of login.
